#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : keditbookmarks
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/keditbookmarks-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/keditbookmarks-18.08.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0
Requires: keditbookmarks-bin
Requires: keditbookmarks-lib
Requires: keditbookmarks-data
Requires: keditbookmarks-license
Requires: keditbookmarks-locales
Requires: keditbookmarks-man
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
No detailed description available

%package bin
Summary: bin components for the keditbookmarks package.
Group: Binaries
Requires: keditbookmarks-data
Requires: keditbookmarks-license
Requires: keditbookmarks-man

%description bin
bin components for the keditbookmarks package.


%package data
Summary: data components for the keditbookmarks package.
Group: Data

%description data
data components for the keditbookmarks package.


%package dev
Summary: dev components for the keditbookmarks package.
Group: Development
Requires: keditbookmarks-lib
Requires: keditbookmarks-bin
Requires: keditbookmarks-data
Provides: keditbookmarks-devel

%description dev
dev components for the keditbookmarks package.


%package doc
Summary: doc components for the keditbookmarks package.
Group: Documentation
Requires: keditbookmarks-man

%description doc
doc components for the keditbookmarks package.


%package lib
Summary: lib components for the keditbookmarks package.
Group: Libraries
Requires: keditbookmarks-data
Requires: keditbookmarks-license

%description lib
lib components for the keditbookmarks package.


%package license
Summary: license components for the keditbookmarks package.
Group: Default

%description license
license components for the keditbookmarks package.


%package locales
Summary: locales components for the keditbookmarks package.
Group: Default

%description locales
locales components for the keditbookmarks package.


%package man
Summary: man components for the keditbookmarks package.
Group: Default

%description man
man components for the keditbookmarks package.


%prep
%setup -q -n keditbookmarks-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535197120
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535197120
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/keditbookmarks
cp COPYING %{buildroot}/usr/share/doc/keditbookmarks/COPYING
cp COPYING.DOC %{buildroot}/usr/share/doc/keditbookmarks/COPYING.DOC
pushd clr-build
%make_install
popd
%find_lang keditbookmarks

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kbookmarkmerger
/usr/bin/keditbookmarks

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.keditbookmarks.desktop
/usr/share/config.kcfg/keditbookmarks.kcfg
/usr/share/kxmlgui5/keditbookmarks/keditbookmarks-genui.rc
/usr/share/kxmlgui5/keditbookmarks/keditbookmarksui.rc

%files dev
%defattr(-,root,root,-)
/usr/lib64/libkbookmarkmodel_private.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/ca/keditbookmarks/index.docbook
/usr/share/doc/HTML/de/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/de/keditbookmarks/index.docbook
/usr/share/doc/HTML/en/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/en/keditbookmarks/index.docbook
/usr/share/doc/HTML/es/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/es/keditbookmarks/index.docbook
/usr/share/doc/HTML/it/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/it/keditbookmarks/index.docbook
/usr/share/doc/HTML/nl/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/nl/keditbookmarks/index.docbook
/usr/share/doc/HTML/pt/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/pt/keditbookmarks/index.docbook
/usr/share/doc/HTML/sv/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/sv/keditbookmarks/index.docbook
/usr/share/doc/HTML/uk/keditbookmarks/index.cache.bz2
/usr/share/doc/HTML/uk/keditbookmarks/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkbookmarkmodel_private.so.5.97.0
/usr/lib64/libkbookmarkmodel_private.so.6

%files license
%defattr(-,root,root,-)
/usr/share/doc/keditbookmarks/COPYING
/usr/share/doc/keditbookmarks/COPYING.DOC

%files man
%defattr(-,root,root,-)
/usr/share/man/ca/man1/kbookmarkmerger.1
/usr/share/man/da/man1/kbookmarkmerger.1
/usr/share/man/de/man1/kbookmarkmerger.1
/usr/share/man/el/man1/kbookmarkmerger.1
/usr/share/man/es/man1/kbookmarkmerger.1
/usr/share/man/et/man1/kbookmarkmerger.1
/usr/share/man/fr/man1/kbookmarkmerger.1
/usr/share/man/it/man1/kbookmarkmerger.1
/usr/share/man/man1/kbookmarkmerger.1
/usr/share/man/nb/man1/kbookmarkmerger.1
/usr/share/man/nl/man1/kbookmarkmerger.1
/usr/share/man/pl/man1/kbookmarkmerger.1
/usr/share/man/pt/man1/kbookmarkmerger.1
/usr/share/man/pt_BR/man1/kbookmarkmerger.1
/usr/share/man/ru/man1/kbookmarkmerger.1
/usr/share/man/sr/man1/kbookmarkmerger.1
/usr/share/man/sv/man1/kbookmarkmerger.1
/usr/share/man/uk/man1/kbookmarkmerger.1

%files locales -f keditbookmarks.lang
%defattr(-,root,root,-)

